name: Pulumi up
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  network:
    name: Update ${{ matrix.stack.name}}
    runs-on: ubuntu-latest
    environment: ${{ matrix.stack.name }}
    strategy:
      matrix:
        stack: [
          { name: "development", role: AWS_OIDC_DEVELOPMENT_ROLE_ARN },
          { name: "sandbox", role: AWS_OIDC_PRODUCTION_ROLE_ARN }
        ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets[matrix.stack.role] }}
          role-session-name: githubactions
          aws-region: us-east-1
      - name: Verify permissions
        run: |
          aws sts get-caller-identity
      - name: Deploy AWS VPC
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ matrix.stack.name}}
          work-dir: aws/vpc
